version: '3.7'

services:

  db:
    container_name: db_mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_DATABASE: local_db
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
       - "3306:3306"
